[features]
seeds = false
[programs.devnet]
metaplex_anchor_nft = "4jNNoXXRZA8ctduQWkea3TPxN2TLYCfJNxyjEPs5Bu7W"

[registry]
url = "https://api.devnet.solana.com"
[provider]
cluster = "https://api.devnet.solana.com"
wallet = "./wallet1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/initialize.ts"
initialize = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/initialize.ts"